#!/usr/bin/perl -w
# created by Zhouliang
# fetch index and ip of cpe, and make a hash table

($sec,$min,$hour,$day,$mon,$year) = localtime;
($sec,$min,$hour,$day,$mon,$year) = (
    sprintf("%02d", $sec),
    sprintf("%02d", $min),
    sprintf("%02d", $hour),
    sprintf("%02d", $day),
    sprintf("%02d", $mon + 1),
    $year + 1900
);
$filenameprefix="/var/ip/" . $year . $mon . $day;
mkdir($filenameprefix,0777);

while(<>)
{
        $cmts = $_;

        chomp($cmts);
        $cmd = "snmpwalk -c public -O uqx -v 2c " . $cmts . " 1.3.6.1.2.1.10.127.1.3.3.1.2";
        foreach $_ (`$cmd`)
        {
                ($index, $mac1, $mac2, $mac3, $mac4, $mac5, $mac6) = /(\S+)\W+(\w+)\W+(\w+)\W+(\w+)\W+(\w+)\W+(\w+)\W+(\w+)/;
                @index = split(/\./,$index);
                $index = $index[7];
                $mac = $mac1 . $mac2 . "." . $mac3 . $mac4 . "." . $mac5 . $mac6;
                $indexmac{$index} = $mac;
        }


        $filename = $filenameprefix . "/" . $cmts;
        open(LOG, ">>$filename");

        $currenttime=localtime();

        $cmd = "snmpwalk -c public -O uqx -v 2c " . $cmts . " 1.3.6.1.3.83.4.1.5.1.2";
        foreach $_ (`$cmd`)
        {
                ($index, $ip1, $ip2, $ip3, $ip4) = /(\S+)\W+(\w+)\W+(\w+)\W+(\w+)\W+(\w+)/;
                @index = split(/\./,$index);
                $index = $index[6];
                $ip1 = hex($ip1);
               #if ($ip1=="10")
               #{
               #         next;
               #}
                $ip2 = hex($ip2);
                $ip3 = hex($ip3);
                $ip4 = hex($ip4);
                $ip = $ip1 . "." . $ip2 . "." . $ip3 . "." .  $ip4;
                $log = $cmts . " " . $currenttime . "   " . $ip . "     " . $indexmac{$index} . "\n";
                print LOG $log;
        }
        close(LOG);
}
