#!/usr/bin/perl -w
# created by Zhouliang
# fetch index and ip of cpe, and make a hash table

($sec,$min,$hour,$day,$mon,$year) = localtime;
($sec,$min,$hour,$day,$mon,$year) = (
    sprintf("%02d", $sec),
    sprintf("%02d", $min),
    sprintf("%02d", $hour),
    sprintf("%02d", $day),
    sprintf("%02d", $mon + 1),
    $year + 1900
);
$filenameprefix="/var/ip/" . $year . $mon . $day;
mkdir($filenameprefix,0777);

while(<>)
{
        $cmts = $_;

        chomp($cmts);
        $filename = $filenameprefix . "/" . $cmts;
        open(LOG, ">>$filename");

        $currenttime=localtime();

        $cmd = "snmpwalk -c cnt2001jsB -O uqx -v 2c " . $cmts . " 1.3.6.1.4.1.32285.11.1.1.2.10.5.1.3";
        foreach $_ (`$cmd`)
        {
                ($ip, $mac1, $mac2, $mac3, $mac4, $mac5, $mac6) = /(\S+)\W+(\w+)\W+(\w+)\W+(\w+)\W+(\w+)\W+(\w+)\W+(\w+)/;
                $mac = $mac1 . $mac2 . "." . $mac3 . $mac4 . "." . $mac5 . $mac6;
                @ip = split(/\./,$ip);
				#if($ip[10]=="10"){
				#	next;
				#}
                $ip = $ip[10] . "." . $ip[11] . "." . $ip[12] . "." . $ip[13];
                $log = $cmts . " " . $currenttime . "   " . $ip . "     " . $mac . "\n";
                print LOG $log;
        }
        close(LOG);
}
